src/Entity/Event.php
<?php

namespace App\Entity;

use App\Repository\EventRepository;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Validator\Constraints as Assert;


/**
 * @ORM\Entity(repositoryClass=EventRepository::class)
 */
class Event
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=50, nullable=true)
     * @Assert\Length(max="30", maxMessage="Votre titre ne doit depasser 30 caractéres")
     */
    private $titre;

    /**
     * @ORM\Column(type="string", length=100, nullable=true)
     */
    private $description;

    /**
     * @ORM\Column(type="string", length=100, nullable=true)
     */
    private $image;

    /**
     * @ORM\Column(type="string", length=500, nullable=true)
     */
    private $location;

    /**
     * @return mixed
     */
    public function getLocation()
    {
        return $this->location;
    }

    /**
     * @param mixed $location
     */
    public function setLocation($location): void
    {
        $this->location = $location;
    }



    /**
     * @return mixed
     */
    public function getImage()
    {
        return $this->image;
    }

    /**
     * @param mixed $image
     */
    public function setImage($image): void
    {
        $this->image = $image;
    }



    /**
     * @ORM\Column(type="datetime", nullable=true)
     */
    private $dateDebut;

    /**
     * @ORM\Column(type="datetime", nullable=true)
     */
    private $DateFin;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getTitre(): ?string
    {
        return $this->titre;
    }

    public function setTitre(?string $titre): self
    {
        $this->titre = $titre;

        return $this;
    }

    public function getDescription(): ?string
    {
        return $this->description;
    }

    public function setDescription(?string $description): self
    {
        $this->description = $description;

        return $this;
    }

    public function getDateDebut(): ?\DateTimeInterface
    {
        return $this->dateDebut;
    }

    public function setDateDebut(?\DateTimeInterface $dateDebut): self
    {
        $this->dateDebut = $dateDebut;

        return $this;
    }

    public function getDateFin(): ?\DateTimeInterface
    {
        return $this->DateFin;
    }

    public function setDateFin(?\DateTimeInterface $DateFin): self
    {
        $this->DateFin = $DateFin;

        return $this;
    }
}

src/Controller/PromoController.php
<?php

namespace App\Controller;

use App\Entity\Promotion;
use App\Form\PromotionType;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Component\HttpFoundation\Session\SessionInterface;

class PromoController extends AbstractController
{
    protected $session;
    public function __construct(SessionInterface $session)
    {
        $this->session = $session;
    }

    private function isAuth() {
        if(is_null($this->session->get('user'))){
        return false;
        }
        // $user = $this->getDoctrine()->getRepository(User::class)->find($this->session->get('user')->getId());
        // if ($user->getBan()) {
        //   $this->session->clear();
        //   return false;
        // }
        return true;
    }

    private function isAdmin() {
        if(is_null($this->session->get('user'))||$this->session->get('user')->getRole()!="admin"){
        return false;
        }
        // $user = $this->getDoctrine()->getRepository(User::class)->find($this->session->get('user')->getId());
        // if ($user->getBan()) {
        //   $this->session->clear();
        //   return false;
        // }
        return true;
    }

    /**
     * @Route("/admin/promos", name="admin_promos")
     */
    public function promoList(Request $request, EntityManagerInterface $manager): Response
    {
        if (!$this->isAdmin())
            return $this->redirectToRoute('login');
        $promos = $this->getDoctrine()->getRepository(Promotion::class)->findAll();

        $promo = new Promotion();
        $form = $this->createForm(PromotionType::class, $promo);
        $form->handleRequest($request);
        if($form->isSubmitted() && $form->isValid()){
            $manager->persist($promo);
            $manager->flush();
            return $this->redirectToRoute('admin_promos');
        }
        return $this->render('pages/admin/promo/liste_promo.html.twig', ["form"=>$form->createView(), "promos"=>$promos]);
    }

    /**
     * @Route("admin/update-promo/{id}", name="update_promo")
     */
    public function update(Request $request, EntityManagerInterface $manager, $id): Response
    {
        if (!$this->isAdmin())
            return $this->redirectToRoute('login');
        if ($request->isMethod('post')) {
            // your code
            $promo = $this->getDoctrine()->getRepository(Promotion::class)->find($id);
            $promo->setTitre($request->request->get('titre'));
            $promo->setTypeProduit($request->request->get('type_produit'));
            $promo->setPourcentage($request->request->get('pourcentage'));
            $promo->setDescription($request->request->get('description'));
            $promo->setDateDebut(\DateTime::createFromFormat('Y-m-d', $request->request->get('DateDebut')));
            $promo->setDateFin(\DateTime::createFromFormat('Y-m-d', $request->request->get('DateFin')));


            $manager->flush();
            return $this->redirectToRoute('admin_promos');
        }

    }

    /**
     * @Route("/admin/delete-promo/{id}", name="delete_promo")
     */
    public function delete($id, EntityManagerInterface $manager): Response
    {
        if (!$this->isAdmin())
            return $this->redirectToRoute('login');
        $promo = $this->getDoctrine()->getRepository(Promotion::class)->find($id);
        $manager->remove($promo);
        $manager->flush();
        return $this->redirectToRoute('admin_promos');
    }
    /**
     * @return string
     */
    private function generateUniqueFileName()
    {
        return md5(uniqid());
    }


}

templates/pages/admin/promo/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Hello PromoController!{% endblock %}

{% block body %}
<style>
    .example-wrapper { margin: 1em auto; max-width: 800px; width: 95%; font: 18px/1.5 sans-serif; }
    .example-wrapper code { background: #F5F5F5; padding: 2px 6px; }
</style>

<div class="example-wrapper">
    <h1>Hello {{ controller_name }}! ✅</h1>

    This friendly message is coming from:
    <ul>
        <li>Your controller at <code><a href="{{ 'C:/Users/Kais/Documents/sporify_web/src/Controller/PromoController.php'|file_link(0) }}">src/Controller/PromoController.php</a></code></li>
        <li>Your template at <code><a href="{{ 'C:/Users/Kais/Documents/sporify_web/templates/promo/index.html.twig'|file_link(0) }}">templates/promo/index.html.twig</a></code></li>
    </ul>
</div>
{% endblock %}

templates/pages/admin/promo/liste_promo.html.twig
{% extends 'layout/admin/index.html.twig' %}

{% block title %}
<title>Promo - Admin</title>
{% endblock %}

{% block subtitle %}
<a class="navbar-brand" href="javascript:;">Promos</a>
{% endblock %}

{% block body %}
    <div class="content">
        <div style="display: flex; align-items: center; justify-content: space-between">
            <h1 style="margin-right: 20px">Liste des Promotions</h1>
            <button data-bs-toggle="modal" data-bs-target="#addModal" class="btn btn-outline-success" style="width: 100px"><i class="nc-icon nc-simple-add" style="font-size: 28px"></i></button>
        </div>
        <br>
        {% if form.pourcentage.vars.errors|length %}
            <div class="col-sm-12 alert alert-danger">{{ form_errors(form.pourcentage) }}</div>
        {% endif %}
        <br>
        <table class="table table-hover">
            <thead>
            <tr>
                <th scope="col">Pourcentage</th>
                <th scope="col">Titre</th>
                <th scope="col">Description</th>
                <th scope="col">Date debut</th>
                <th scope="col">Date fin</th>
                <th scope="col">Type produit</th>
                <th scope="col">Actions</th>
            </tr>
            </thead>
            <tbody>
            {% for promo in promos %}
                <tr>
                    <td >{{ promo.pourcentage }}</td>
                    <td >{{ promo.titre }}</td>
                    <td>{{ promo.description }}</td>
                    <td>{{ promo.DateDebut|date("m-d-Y") }}</td>
                    <td>{{ promo.DateFin|date("m-d-Y") }}</td>
                    <td>{{ promo.typeProduit }}</td>
                    <td><div style="display: flex">

                            <button class="btn btn-outline-warning" data-bs-toggle="modal" data-bs-target="#updateModal{{ promo.id }}" style="margin-right: 10px"><i class="nc-icon nc-settings"></i></button>

                            <button class="btn btn-outline-danger" data-bs-toggle="modal" data-bs-target="#deleteModal{{ promo.id }}"><i class="nc-icon nc-simple-delete"></i></button>

                        </div>
                    </td>
                </tr>
                <!-- Delete Modal -->
              <div class="modal fade" id="deleteModal{{ promo.id }}" tabindex="-1" aria-hidden="true">
                    <div class="modal-dialog">
                        <div class="modal-content">
                            <div class="modal-body">
                                <br>
                                <h5 class="modal-title" id="exampleModalLabel">Voulez vous supprimer la promotion {{ promo.titre }}</h5>
                                <br>
                                <div style="text-align: center">
                                    <a type="button" href="{{ path('delete_promo', {'id':promo.id}) }}" class="btn btn-danger">Supprimer</a>
                                    <a type="button" class="btn btn-secondary" data-dismiss="modal">Fermer</a>
                                </div>
                                <br>
                            </div>

                        </div>
                    </div>
                </div>


                <!--  Update Modal -->
                <div class="modal fade" id="updateModal{{ promo.id }}" tabindex="-1" aria-hidden="true">
                    <div class="modal-dialog modal-lg">
                        <div class="modal-content">
                            <form method="post" action="{{ path('update_promo', {'id':promo.id}) }}" enctype="multipart/form-data">
                                <div class="modal-header">
                                    <h5 class="modal-title" id="exampleModalLabel">Modifier la promotion </h5>
                                    <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                                </div>
                                <div class="modal-body">
                                    <br>
                                    <div class="form-group row">
                                        <div class="col-md-12">
                                            <label class="form__label">Titre</label>
                                            <input type="text" maxlength="30" name="titre" value="{{ promo.titre }}" class="form-control">
                                        </div>
                                    </div>
                                    <br>

                                    <div class="form-group row">
                                        <div class="col-md-12">
                                            <label class="form__label">Type de produit</label>
                                            <select name="type_produit" class="form-control">
                                                <option value="{{ promo.typeProduit }}" selected>{{ promo.typeProduit }}</option>
                                                <option value="Tshirts">Tshirts</option>
                                                <option value="Vestes">Vestes</option>
                                                <option value="Equipement">Equipement</option>
                                                <option value="Pantalons">Pantalons</option>
                                                <option value="Accessoires">Accessoires</option>
                                            </select>

                                        </div>
                                    </div>
                                    <br>
                                    <div class="form-group row">
                                        <div class="col-md-12">
                                            <label class="form__label">Pourcentage</label>
                                            <input type="number" min="1" max="99" name="pourcentage" value="{{ promo.pourcentage }}" class="form-control">
                                        </div>
                                    </div>
                                    <br>

                                    <br>
                                    <div class="form-group row">
                                        <div class="col-md-12">
                                            <label class="form__label">Description</label>
                                            <textarea name="description" class="form-control">{{ promo.description }}</textarea>
                                        </div>
                                    </div>
                                    <br>
                                    <div class="form-group row">
                                        <div class="col-md-12">
                                            <label class="form__label">Date debut</label>
                                            <input type="date" name="DateDebut" value="{{ promo.dateDebut|date('Y-m-d') }}" class="form-control">
                                        </div>
                                    </div>
                                    <br>
                                    <div class="form-group row">
                                        <div class="col-md-12">
                                            <label class="form__label">Date fin</label>
                                            <input type="date" name="DateFin" value="{{ promo.dateFin|date('Y-m-d') }}" class="form-control">
                                        </div>
                                    </div>
                                    <br>
                                <div class="modal-footer">
                                    <button type="submit" class="btn btn-primary">Modifier</button>
                                    <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Fermer</button>
                                </div>
                                </div>
                            </form>
                        </div>
            </div>

            {% endfor %}
                </div>
            </tbody>

        </table>
    </div>


    <!-- Add Modal -->
    <div class="modal fade" id="addModal" tabindex="-1" aria-hidden="true">
        <div class="modal-dialog modal-lg">
            <div class="modal-content">
                {{ form_start(form, {'attr': {'enctype':'multipart/form-data'}}) }}
                <div class="modal-header">
                    <h5 class="modal-title" id="exampleModalLabel">Ajouter une nouvelle Promotion</h5>
                    <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                </div>
                <div class="modal-body">
                    <br>
                    <div class="form-group row">
                        <div class="col-md-12">
                            <label class="form__label">Titre</label>
                            {{ form_widget(form.titre, {'attr': {'placeholder': 'Titre du projet', 'class':'form-control', 'type':'text'}}) }}
                        </div>
                    </div>
                    <br>
                    <div class="form-group row">
                        <div class="col-md-12">
                            <label class="form__label">Pourcentage</label>
                            {{ form_widget(form.pourcentage, {'attr': {'placeholder': 'Pourcentage du projet', 'class':'form-control'}}) }}
                        </div>
                    </div>
                    <div class="form-group row">
                        <div class="col-md-12">
                            <label class="form__label">Type de produit</label>
                            {{ form_widget(form.typeProduit, {'class':'form-control'}) }}
                        </div>
                    </div>
                    <div class="form-group row">

                        <div class="col-md-12">
                            <label class="form__label">Description</label>
                            {{ form_widget(form.description, {'attr': {'placeholder': 'Description du projet', 'class':'form-control', 'type':'text'}}) }}
                        </div>
                    </div>
                    <br>
                    <div class="form-group row">

                        <div class="col-md-12">
                            <label class="form__label">Date debut</label>
                            {{ form_widget(form.date_debut, {'attr': {'class':'form-control'}}) }}
                        </div>
                    </div>
                    <br>
                    <div class="form-group row">
                        <div class="col-md-12">
                            <label class="form__label">Date fin</label>
                            {{ form_widget(form.date_fin, {'attr': {'class':'form-control'}}) }}
                        </div>
                    </div>
                    <br>
                </div>
                <div class="modal-footer">
                    <button type="submit" class="btn btn-primary">Enregistrer</button>
                    <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Fermer</button>
                </div>
                {{ form_end(form) }}
            </div>
        </div>
    </div>


{% endblock %}

templates/pages/admin/promo/liste_promo_front.html.twig
{% extends 'base_front.html.twig' %}


{% block body %}

{% endblock %}